### ISSUE TITLE
Develop a tool to download parcels for the a given case study

### ISSUE THREAD

**Issue by qjhart** [CSTARS/ahb-case-studies#2]
Our partners with AHB have developed an online Parcel [Feature Service](https://conifer.gis.washington.edu/arcgis/rest/services/AHBNW/AHBNW_20151009_parcel_featureAccess/FeatureServer/0) 

The hope is that we will be able to use this service to load our case studies, (as well as our decision support tools) using this dataset.   The idea is to develop a script which given a point will download all the close parcels for that point.  The output of this is a table in our database.  Maybe a first pass looks like:

```{bash}
ahb.parcels --site=-122,43  --distance=200 --output=dsn
```

Where site is a longitude, latitude combination, distance is the radius of the cirle, and _output_ is the GDAL output dsn. This looks possible in node.js I think.

**Comment by jrmerz** [comment]
I have started a new 'SDK' assuming it will be the backbone of the decision support app as well as this study. https://github.com/CSTARS/ahb-decision-support-sdk.

The following will run that sample code which does a 3km bbox query at a point around redding against the WU arcgis service.  Then looks up soil and weather for the parcels and finally runs the poplar growth model for each parcel.
```JavaScript
git clone https://github.com/CSTARS/ahb-decision-support-sdk
cd ahb-decision-support-sdk && npm install
node sample.js
```

For this specific issue, the SDK.rest.parcels.get(lat, lng, radius, callback) function should do the trick.  Obviously I need to add command line support.  Perhaps we write the command line parser code in this repo?  You can see a sample query here: https://github.com/CSTARS/ahb-decision-support-sdk/blob/master/tests/rest/parcels.js#L9.  Note, this function translates ArcGIS JSON to GeoJSON.  So the response signature is function(error, [geojson]).

**Comment by qjhart** [comment]
Justin has added this functionality into the above ahb-decision-support-sdk.
